%YAML:1.0
---
model_type: PINHOLE
camera_name: cam0
image_width: 752
image_height: 480
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 4.6925e+02
   fy: 4.6925e+02
   cx: 3.7650e+02
   cy: 2.4050e+02
